### PR TITLE
23 cd adding continuous deployments to the project

### LINKED ISSUE #23: CD - Adding continuous deployments to the project
Currently, to deploy to NPM we have to bump the version by hand, build and then deploy.
This process is all done locally but feels like it can be automated.

We would like to do the following steps:
- Build the project
- Bump the minor versions of all projects by 1
- Commit/Push the changes to Git
- Make a branch out of new release -> "release/x.x.x"
- Tag the release
- Deploy all projects to npm

When needed to setup secrets, please let me know we will take care of it at that time!

### PR DESCRIPTION
**Pull request by andy2great**
# Description

Adding capability to deploy all packages that are publishable!
Here are example of what occures:
image
image
image

Please merge #24 before merging this pr

Fixes #23

Thank you for contributing to our NX-Generatorz repo!
:rocket:(づ｡◕‿‿◕｡)づ:rocket:

### CODE REVIEW

**Review by MeatCow — APPROVED** [review]
LGTM

**Comment by MeatCow** [comment]
One change I would suggest is to maybe have a bot account for doing the deployments. What do you think?

**Comment by andy2great** [comment]
> ing the deployments. What do you



> One change I would suggest is to maybe have a bot account for doing the deployments. What do you think?

NOP V-V this makes me cry everyday :<

**Comment by MeatCow** [comment]
Looks like npmjs doesn't support service accounts for the CD step of the deployment phase. A feature we'll have to live without :(

**Comment by andy2great** [comment]
lets make our own npm 🚀

**Pull request merged**
